# Generated by Django 5.0.4 on 2024-08-18 11:27

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
        ('menu', '0012_alter_main_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(max_length=200, verbose_name='شماره تماس')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('description', models.CharField(max_length=4000, verbose_name='توضیحات')),
                ('answer', models.CharField(max_length=4000, verbose_name='جواب')),
                ('active', models.BooleanField(default=False, verbose_name='فعالیت')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.main', verbose_name='صفحه')),
            ],
        ),
    ]
