# Generated by Django 5.0.7 on 2024-07-23 15:33

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='نوع اسلایدر')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousels/main/', verbose_name='عکس')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک')),
                ('short_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کوتاه')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات')),
                ('view_in', models.IntegerField(default=0, verbose_name='مشاهده در')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
