# Generated by Django 5.0.14 on 2025-05-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousels', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sliders',
            name='view_in',
        ),
    ]
