# Generated by Django 5.0.7 on 2024-07-23 15:33

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/notices/', verbose_name='عکس')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('titleseo', models.CharField(max_length=200, verbose_name='عنوان سئو')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن توضیحی')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('titleseo', models.CharField(max_length=200, verbose_name='عنوان سئو')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('short_text', models.CharField(max_length=200, verbose_name='متن کوتاه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('hot', models.BooleanField(default=False, verbose_name='ویژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/notices/', verbose_name='عکس')),
                ('keywords', models.CharField(blank=True, max_length=4000, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن توضیحی')),
                ('view_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('newscat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.category', verbose_name='گروه')),
            ],
        ),
    ]
