# Generated by Django 5.0.4 on 2024-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(max_length=200, verbose_name='متن کوتاه'),
        ),
    ]
