"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&32^me-=t@dxmmj*a907m0c5d$a8^i#rzjjs+kao%qczqbk3*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'userauth.backend.MobileBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # extenalApps
    'sorl.thumbnail',

    # admin apps
    'persianfonts.apps.PersianfontsConfig',
    'userauth.apps.UserauthConfig',
    'membership.apps.MembershipConfig',
    'notices.apps.NoticesConfig',
    'menu.apps.MenuConfig',
    'carousels.apps.CarouselsConfig',
    'smsir.apps.SmsirConfig',
    'adminsortable2',
    'django_jalali',
    'admin_auto_filters',
    'ckeditor',
    'ckeditor_uploader',
    'website.apps.WebsiteConfig',
    'portfolio.apps.PortfolioConfig',
    'faq.apps.FaqConfig',
    'products.apps.ProductsConfig',


    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  
        'NAME': 'poosam.net',                         
        'USER': 'postgres',                     
        'PASSWORD': 'qweQWE',
        'HOST': 'localhost',                         
        'PORT': '',                                 
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [
    BASE_DIR / 'assets'
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

# CkEditor Config
CKEDITOR_UPLOAD_PATH = "uploads/"
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         'skin': 'moono',
#         # 'font_names': 'Vazir',
#         # 'contentsCss': ['https://fonts.googleapis.com/css?family=Vazirmatn']
#         # 'skin': 'office2013',
#         'contentsCss': 'http://127.0.0.1:8000/static/persian_fonts/css/all.css',
#         'font_names': 'sahel;samim;shabnam;tanha;vazir;yekan;parastoo;',
#         # 'toolbar_Basic': [
#         #     ['Source', '-', 'Bold', 'Italic']
#         # ],
#         # 'toolbar_YourCustomToolbarConfig': [
#         #     {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
#         #     {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
#         #     {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
#         #     {'name': 'forms',
#         #      'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
#         #                'HiddenField']},
#         #     '/',
#         #     {'name': 'basicstyles',
#         #      'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
#         #     {'name': 'paragraph',
#         #      'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
#         #                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
#         #                'Language']},
#         #     {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
#         #     {'name': 'insert',
#         #      'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
#         #     '/',
#         #     {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
#         #     {'name': 'colors', 'items': ['TextColor', 'BGColor']},
#         #     {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
#         #     {'name': 'about', 'items': ['About']},
#         #     '/',  # put this to force next toolbar on new line
#         #     {'name': 'yourcustomtools', 'items': [
#         #         # put the name of your editor.ui.addButton here
#         #         'Preview',
#         #         'Maximize',
#         #
#         #     ]},
#         # ],
#         # 'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
#         # # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
#         # # 'height': 291,
#         # # 'width': '100%',
#         # # 'filebrowserWindowHeight': 725,
#         # # 'filebrowserWindowWidth': 940,
#         # # 'toolbarCanCollapse': True,
#         # # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
#         # 'tabSpaces': 4,
#         # 'extraPlugins': ','.join([
#         #     'uploadimage', # the upload image feature
#         #     # your extra plugins here
#         #     'div',
#         #     'autolink',
#         #     'autoembed',
#         #     'embedsemantic',
#         #     'autogrow',
#         #     # 'devtools',
#         #     'widget',
#         #     'lineutils',
#         #     'clipboard',
#         #     'dialog',
#         #     'dialogui',
#         #     'elementspath'
#         # ]),
#     }
# }

# Create Memebership Users
AUTH_USER_MODEL = 'membership.Users'

# SMS
API_KEY = 'e6z6N1JbRmXdHrfIxWTBEJg9hFLahn2ag7Peoblc8Vs3VxpGnRN0IMcxjRnS2mJP'
LINENUMBER = '3000463163'
LOGOUT_REDIRECT_URL = '/'


# start sorl thumbnail config

# خروجی WebP به صورت پیش‌فرض
THUMBNAIL_FORMAT = 'WEBP'

# مسیر ذخیره‌ی thumbnailها
THUMBNAIL_PREFIX = 'cache/'

# موتور کش: می‌تونی redis یا memcached بذاری، یا همون فایل‌سیستم
THUMBNAIL_KVSTORE = 'sorl.thumbnail.kvstores.cached_db_kvstore.KVStore'

# زمان کش
THUMBNAIL_CACHE_TIMEOUT = 60 * 60 * 24 * 30  # 30 روز

# سطح فشرده‌سازی
THUMBNAIL_QUALITY = 85

# THUMBNAIL_FORCE_OVERWRITE = True



# مشخص کردن پسوند به صورت دستی (در صورت نیاز)
# THUMBNAIL_EXTENSION = 'webp'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
# end sorl thumbnail config