# Generated by Django 5.0.7 on 2024-07-23 15:33

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('titleseo', models.CharField(max_length=200, verbose_name='عنوان سئو')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('showCmnt', models.BooleanField(default=False, verbose_name='نمایش نظرات')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن توضیحی')),
                ('canonical', models.CharField(blank=True, max_length=500, verbose_name='لینک canonical')),
                ('noindexnofollow', models.BooleanField(default=True, verbose_name='ایندکس صفحه')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sub_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.main', verbose_name='زیر مجموعه')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
