# Generated by Django 5.0.7 on 2024-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='display',
            field=models.BooleanField(default=True, verbose_name='نمایش'),
        ),
    ]
