# Generated by Django 5.0.7 on 2024-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_main_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='mostVisited',
            field=models.BooleanField(default=False, verbose_name='نمایش در پربازدیدها'),
        ),
        migrations.AddField(
            model_name='main',
            name='showHome',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
