# Generated by Django 5.0.7 on 2024-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_main_mostvisited_main_showhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/manu/', verbose_name='عکس'),
        ),
    ]
