# Generated by Django 5.0.7 on 2024-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='orginal_image',
            field=models.CharField(default='', max_length=100, verbose_name='عکس اصلی'),
            preserve_default=False,
        ),
    ]
