# Generated by Django 5.0.7 on 2024-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_main_orginal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='orginal_image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عکس اصلی'),
        ),
    ]
