# Generated by Django 5.0.7 on 2024-07-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_main_orginal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='image',
        ),
    ]
