# Generated by Django 5.0.7 on 2024-07-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='orginal_image',
            new_name='image',
        ),
    ]
