# Generated by Django 5.0.4 on 2024-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_orginal_image_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='متن توضیحی'),
        ),
    ]
