# Generated by Django 5.0.4 on 2024-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_main_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='متن توضیحی'),
        ),
    ]
