# Generated by Django 5.0.4 on 2024-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_main_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='keywords',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
