# Generated by Django 5.0.14 on 2025-05-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_urlcatergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='show_id',
            field=models.CharField(default=1, max_length=200, verbose_name='شناسه نمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='url_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.urlcatergory', verbose_name='دسته بندی لینک'),
            preserve_default=False,
        ),
    ]
