# Generated by Django 5.0.14 on 2025-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_main_show_id_main_url_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='show_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه نمایش'),
        ),
    ]
