# Generated by Django 5.0.14 on 2025-05-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_main_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='url_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.urlcatergory', verbose_name='دسته بندی لینک'),
        ),
    ]
