# Generated by Django 5.0.14 on 2025-05-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_main_url_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='url_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='menu.urlcatergory', verbose_name='دسته بندی لینک'),
        ),
    ]
