# Generated by Django 5.0.4 on 2024-09-07 11:34

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0012_alter_main_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.main', verbose_name='زیر مجموعه')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/products/', verbose_name='عکس')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('m_created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن میلادی')),
                ('sh_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن شمسی')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.main', verbose_name='زیر مجموعه')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.detailstitle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
