# Generated by Django 5.0.4 on 2024-09-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_main_keywords'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product',
            field=models.IntegerField(default=1, verbose_name='زیر مجموعه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.main', verbose_name='دسته بندی'),
        ),
    ]
