# Generated by Django 5.0.4 on 2024-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_alter_products_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailstitle',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
    ]
