# Generated by Django 5.0.4 on 2024-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_detailstitle_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
    ]
