# Generated by Django 5.0.14 on 2025-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_url_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='show_id',
            field=models.CharField(default=1, max_length=200, verbose_name='شناسه نمایش'),
            preserve_default=False,
        ),
    ]
