# Generated by Django 5.0.14 on 2025-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='show_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='شناسه نمایش'),
        ),
    ]
